# Generated by Django 5.0.6 on 2024-07-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsman',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
