<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-07-09 16:42
=======
# Generated by Django 5.0.6 on 2024-07-09 15:39
>>>>>>> origin/users_branch

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportsman',
            name='user',
        ),
    ]
