# Generated by Django 5.0.6 on 2024-07-03 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportsman',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='sportsman',
            name='last_name',
        ),
    ]
