# Generated by Django 5.0.6 on 2024-07-09 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0002_remove_sportsman_user'),
        ('users', '0003_remove_profile_sportsman'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamparticipation',
            name='sportsman_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_participations_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teamparticipation',
            name='sportsman_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_participations_3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teamparticipation',
            name='sportsman_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_participations_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mixedparticipation',
            name='sportsman_M',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mixed_participations_M', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personalparticipation',
            name='sportsman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mixedparticipation',
            name='sportsman_F',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mixed_participations_F', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Sportsman',
        ),
    ]
