# Generated by Django 5.0.6 on 2024-07-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0002_remove_sportsman_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsman',
            name='rank',
            field=models.CharField(blank=True, choices=[('3y', '3-й юношеский'), ('2y', '2-й юношеский'), ('1y', '1-й юношеский'), ('3', '3-й спортивный'), ('2', '2-й спортивный'), ('1', '1-й спортивный'), ('CMS', 'КМС'), ('MS', 'МС'), ('IMS', 'МСМК'), ('Coach', 'Организатор')], max_length=10, null=True),
        ),
    ]
