# Generated by Django 5.0.6 on 2024-07-07 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0004_sportsman_first_name_sportsman_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportsman',
            name='first_name',
        ),
    ]
