# Generated by Django 5.0.6 on 2024-07-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0005_remove_sportsman_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsman',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
