# Generated by Django 5.0.6 on 2024-07-08 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_name', models.CharField(blank=True, max_length=50, null=True)),
                ('sex', models.CharField(choices=[('M', 'Мужчины/Юноши'), ('F', 'Женщины/Девушки')], default='M', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('rank', models.CharField(blank=True, choices=[('3-й юношеский', '3-й юношеский'), ('2-й юношеский', '2-й юношеский'), ('1-й юношеский', '1-й юношеский'), ('3-й спортивный', '3-й спортивный'), ('2-й спортивный', '2-й спортивный'), ('1-й спортивный', '1-й спортивный'), ('КМС', 'КМС'), ('МС', 'МС'), ('МСМК', 'МСМК'), ('Организатор', 'Организатор'), ('Нет разряда', 'Нет разряда')], default='-', max_length=20, null=True)),
                ('region', models.CharField(blank=True, max_length=250, null=True)),
                ('organization', models.CharField(blank=True, max_length=250, null=True)),
                ('coach', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
