# Generated by Django 5.0.6 on 2024-07-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='club',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='grade',
        ),
        migrations.AddField(
            model_name='profile',
            name='coach',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='organization',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='rank',
            field=models.CharField(blank=True, choices=[('3y', '3-й юношеский'), ('2y', '2-й юношеский'), ('1y', '1-й юношеский'), ('3', '3-й спортивный'), ('2', '2-й спортивный'), ('1', '1-й спортивный'), ('CMS', 'КМС'), ('MS', 'МС'), ('IMS', 'МСМК'), ('Coach', 'Организатор'), ('-', 'б/р')], default='-', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='second_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('M', 'Мужчины/Юноши'), ('F', 'Женщины/Девушки')], default='M', max_length=10),
        ),
    ]
