# Generated by Django 5.0.6 on 2024-07-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sport_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
