# Generated by Django 5.0.6 on 2024-07-09 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0004_remove_sportsman_profile'),
        ('users', '0002_profile_sport_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sport_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='sportsman',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='participations.sportsman'),
        ),
    ]
