# Generated by Django 5.0.6 on 2024-07-09 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_sportsman'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sportsman',
        ),
    ]
